server:
  port: 8080
spring:
  profiles:
    active: dev
# mybatis-plus 相关配置
mybatis-plus:
  mapper-locations: classpath*:org/xkx/**/dao/*Dao.xml
  type-aliases-package: org.xkx.**.domain
  global-config:
    banner: false
    db-config:
      idType: AUTO
      logic-delete-value: 0 # 默认值0
      logic-not-delete-value: 1 # 默认值1